require "http/cookie"

module CrDlp
  class CookieJar
    NETSCAPE_HEADER = <<-TEXT
    # Netscape HTTP Cookie File
    # This file is generated by cr-dlp. Do not edit.

    TEXT

    record Cookie,
      domain : String,
      include_subdomains : Bool,
      path : String,
      secure : Bool,
      expires_at : Int64?,
      name : String,
      value : String,
      http_only : Bool = false

    getter filename : String?

    @cookies : Array(Cookie)
    @mutex = Mutex.new

    def self.load(filename : String) : self
      jar = new(filename)
      return jar unless File.exists?(filename)

      File.each_line(filename) do |raw_line|
        line = raw_line.chomp
        next if line.empty?

        http_only = line.starts_with?("#HttpOnly_")
        line = line.lchop("#HttpOnly_") if http_only
        next if line.starts_with?('#')

        fields = line.split('\t', 7)
        unless fields.size == 7
          STDERR.puts("WARNING: skipping malformed cookie line in #{filename}")
          next
        end

        domain, subdomains, path, secure, expires, name, value = fields
        expires_at = expires.to_i64?
        unless expires_at
          STDERR.puts("WARNING: skipping cookie with invalid expiry in #{filename}")
          next
        end
        jar.add(Cookie.new(
          normalize_domain(domain),
          subdomains.upcase == "TRUE",
          normalize_path(path),
          secure.upcase == "TRUE",
          expires_at == 0 ? nil : expires_at,
          name,
          value,
          http_only,
        ))
      end
      jar
    rescue error : File::Error
      raise RequestError.new("Unable to load cookies from #{filename}: #{error.message}", cause: error)
    end

    def initialize(@filename : String? = nil, @cookies = [] of Cookie)
    end

    def size : Int32
      @mutex.synchronize { @cookies.size }
    end

    def absorb(other : CookieJar)
      other.cookies.each { |cookie| add(cookie) }
    end

    def cookies : Array(Cookie)
      @mutex.synchronize { @cookies.dup }
    end

    def add(cookie : Cookie)
      @mutex.synchronize do
        replace_cookie(cookie)
      end
    end

    def header_for(url : String, now = Time.utc) : String?
      uri = URI.parse(url)
      host = uri.hostname.try(&.downcase) || return
      path = uri.path.empty? ? "/" : uri.path
      secure_request = uri.scheme.in?("https", "wss")
      timestamp = now.to_unix

      matches = @mutex.synchronize do
        purge_expired(timestamp)
        @cookies.select do |cookie|
          (!cookie.secure || secure_request) &&
            domain_matches?(cookie, host) &&
            path_matches?(cookie.path, path)
        end.sort_by { |cookie| {-cookie.path.bytesize, cookie.name} }
      end
      return if matches.empty?
      matches.join("; ") { |cookie| "#{cookie.name}=#{cookie.value}" }
    rescue URI::Error
      nil
    end

    def store(headers : HTTP::Headers, request_url : String, now = Time.utc)
      values = headers.get?("Set-Cookie")
      return unless values

      uri = URI.parse(request_url)
      request_host = uri.hostname.try(&.downcase) || return
      changed = false
      values.each do |header|
        parsed_headers = HTTP::Headers{"Set-Cookie" => header}
        HTTP::Cookies.from_server_headers(parsed_headers).each do |source|
          domain_attribute = source.domain
          domain = normalize_domain(domain_attribute || request_host)
          next unless response_domain_valid?(request_host, domain)

          include_subdomains = !domain_attribute.nil?
          path = source.path || default_path(uri.path)
          expires_at = source.expiration_time.try(&.to_unix)
          cookie = Cookie.new(
            domain,
            include_subdomains,
            normalize_path(path),
            source.secure,
            expires_at,
            source.name,
            source.value,
            source.http_only,
          )

          @mutex.synchronize do
            if source.expired?(now)
              changed ||= remove_cookie(cookie)
            else
              replace_cookie(cookie)
              changed = true
            end
          end
        end
      rescue IO::Error | ArgumentError
        STDERR.puts("WARNING: skipping malformed Set-Cookie header from #{request_url}")
      end
      save if changed
    rescue URI::Error
      nil
    end

    def save
      path = @filename
      return unless path

      contents = @mutex.synchronize do
        purge_expired(Time.utc.to_unix)
        String.build do |io|
          io << NETSCAPE_HEADER
          @cookies.sort_by { |cookie| {cookie.domain, cookie.path, cookie.name} }.each do |cookie|
            io << "#HttpOnly_" if cookie.http_only
            io << (cookie.include_subdomains ? ".#{cookie.domain}" : cookie.domain) << '\t'
            io << (cookie.include_subdomains ? "TRUE" : "FALSE") << '\t'
            io << cookie.path << '\t'
            io << (cookie.secure ? "TRUE" : "FALSE") << '\t'
            io << (cookie.expires_at || 0) << '\t'
            io << cookie.name << '\t' << cookie.value << '\n'
          end
        end
      end

      directory = File.dirname(path)
      Dir.mkdir_p(directory) unless directory == "."
      File.write(path, contents)
    rescue error : File::Error
      raise RequestError.new("Unable to save cookies to #{path}: #{error.message}", cause: error)
    end

    private def replace_cookie(cookie : Cookie)
      remove_cookie(cookie)
      @cookies << cookie
    end

    private def remove_cookie(cookie : Cookie) : Bool
      before = @cookies.size
      @cookies.reject! do |existing|
        existing.name == cookie.name &&
          existing.domain == cookie.domain &&
          existing.path == cookie.path
      end
      @cookies.size != before
    end

    private def purge_expired(timestamp : Int64)
      @cookies.reject! do |cookie|
        cookie.expires_at.try { |expires_at| expires_at <= timestamp } || false
      end
    end

    private def domain_matches?(cookie : Cookie, host : String) : Bool
      host == cookie.domain ||
        (cookie.include_subdomains && host.ends_with?(".#{cookie.domain}"))
    end

    private def response_domain_valid?(request_host : String, cookie_domain : String) : Bool
      request_host == cookie_domain || request_host.ends_with?(".#{cookie_domain}")
    end

    private def path_matches?(cookie_path : String, request_path : String) : Bool
      return true if cookie_path == "/"
      return false unless request_path.starts_with?(cookie_path)
      return true if request_path == cookie_path || cookie_path.ends_with?('/')
      request_path.byte_at?(cookie_path.bytesize) == '/'.ord
    end

    private def default_path(request_path : String) : String
      return "/" unless request_path.starts_with?('/')
      separator = request_path.rindex('/')
      return "/" unless separator && separator > 0
      request_path[0, separator]
    end

    private def normalize_domain(domain : String) : String
      domain.strip.downcase.lstrip('.')
    end

    private def normalize_path(path : String) : String
      path.starts_with?('/') ? path : "/"
    end

    private def self.normalize_domain(domain : String) : String
      domain.strip.downcase.lstrip('.')
    end

    private def self.normalize_path(path : String) : String
      path.starts_with?('/') ? path : "/"
    end
  end
end
